package com.ericsson.expr4j.core.exceptions;

public enum ErrorCode {

	INVALID_FACTORIAL_PARAMETER,NUMBER_FORMAT_CONVERSION_ERROR,INVALID_PARAMETER,INVALID_PARAMETER_LENGTH,INTERNAL_ERROR,INVALID_BRACKET_COUNTS;
	
}
